### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by shneorkairois** [mxcezl/authenticated-flask-api#1]
Le fichier api/config.py contient les variables d'environnement nécessaires pour l'application.

Nice work.

**Comment by mxcezl** [comment]
Bonjour,
Je n'ai pas compris le but de cette PR.
Une typo n'est pas respéctée ?

**Comment by shneorkairois** [comment]
Oui la config n'est pas dans le api/config.py c'est juste le point. Le problème peut-être clos je présume.
